site_name: Spellstore
site_description: "A SQLAlchemy centric Feature Store"
site_author: "charliec443"
docs_dir: docs/
repo_name: "charliec443/spellstore"
repo_url: "https://github.com/charliec443/spellstore"
theme:
  name: "material"

markdown_extensions:
  - pymdownx.highlight
  - pymdownx.inlinehilite
  - pymdownx.superfences
  - pymdownx.snippets
  - tables